spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: false
  datasource:
    url: jdbc:mysql://localhost:3306/opt_emplrate
    username: root
    password:
#    username: ${MYSQL_USER:root}
#    password: ${MYSQL_PASSWORD:}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: api-service
    server: http://localhost:${server.port}
    title: API Document
    version: 1.0.0

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: c2VjcmV0QGtleS5hcGlfaGFzX2JlZW5fZGVzaWduZWRfYnlfVGF5TFE=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
  resetKey: 2OeEeG48CvIcH1K0UAXbSo/7gPj3QLJ7MnQZuscRirQ=

api:
  prefix: api/v1
frontend:
  url: http://localhost:5173
